a = input('Digite algo:')
print('O tipo primitivo desse valor é ', type(a))
print('só tem espaço?', a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfanumerico?', a.isalnum())   
print('Esta em maiuscula?', a.isupper())
print('esta em minuscula?', a.islower())
print('Esta capitalizada?', a.istitle())